[build]
rustc-wrapper = "/opt/homebrew/bin/sccache"
target-dir = ".cache/cargo/target"

[alias]
br = "build --release"
rr = "run --release"
cr = "check --release"
tr = "test --release"
m = "make"
nt = "nextest run"
w = "watch"
x = "xtask"

[profile.dev]
split-debuginfo = "unpacked"

[expand]
theme = "TwoDark"
pager = true
