# See https://github.com/topgrade-rs/topgrade/blob/main/config.example.toml
# for a reference

[misc]
# Disable specific steps - same options as the command line flag
disable = [
    "conda",
    "gem",
    "go",
    "helix",
    "node",
    "pip3",
    "ruby_gems",
    "sdkman",
    "system",
    "tmux",
    "uv",
    "vim",
    "vscode",
    "zvm",
]

# don't notify at the end
# https://github.com/topgrade-rs/topgrade/issues/288
skip_notify = true

# Do not set the terminal title
set_title = false

# Whether to self update
no_self_update = true

[brew]
# For the BrewCask step
# If `Repo Cask Upgrade` exists, then use the `-a` option.
# Otherwise, use the `--greedy` option.
greedy_cask = true
