import = [
  "~/.local/share/alacritty/themes/themes/kanagawa_wave.toml",
]
ipc_socket = true
live_config_reload = true

[bell]
duration = 0

[cursor.style]
blinking = "Off"

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.bold]
style = "SemiBold"

[font.bold_italic]
style = "SemiBold Italic"

[font.italic]
style = "Light Italic"

[font.normal]
family = "ComicCodeLigatures Nerd Font"
style = "Light"

[scrolling]
history = 100000

[selection]
save_to_clipboard = false

[window]
decorations = "buttonless"
dynamic_title = true
option_as_alt = "OnlyLeft"
startup_mode = "Windowed"

[shell]
program = "/opt/homebrew/bin/bash"
args = ["--login", "-c", "/usr/local/bin/sessionizer"]
