theme = "onedark"

[lsp]
display-messages = true

[editor]
line-number = "relative"

[keys.normal]
"X" = "extend_line_up"
"G" = "goto_file_end"
"C-up" = "expand_selection"
"C-g" = "extend_search_next"
"C-S-g" = "extend_search_prev"
"C-r" = "rename_symbol"
"A-ret" = "code_action"
"A-[" = "jump_backward"
"A-]" = "jump_forward"
