[[language]]
name = "rust"
language-server = { command = "/Users/knut/.rustup/toolchains/stable-aarch64-apple-darwin/bin/rust-analyzer" }
[language.config]
workspace = { symbol = { search = { kind = "all_symbols", limit = 65536 }}}
procMacro = { enable = true }
#[[language]]
#name = "python"
#language-server = { command = "/opt/homebrew/bin/pylsp" }