[tools]
java = "temurin-21"
node = "latest"
go = "latest"
gradle = "latest"
maven = "latest"
usage = "latest"
jbang = "latest"
ruby = "latest"

[settings]
exec_auto_install = false
not_found_auto_install = false
task_run_auto_install = false

[settings.cargo]
binstall = false
